version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pianobot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lzkghuajgl8t"
s3_prefix = "pianobot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

