AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pianobot
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SaveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pianobot/
      Handler: app.save
      Runtime: nodejs12.x
      Environment:
        Variables:
          BUCKET_NAME: 'pianobot-music'
      Events:
        Save:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /save/{user}
            Method: post

  LoadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pianobot/
      Handler: app.load
      Runtime: nodejs12.x
      Environment:
        Variables:
          BUCKET_NAME: 'pianobot-music'
      Events:
        Load:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /load/{user}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SaveApi:
    Description: "API Gateway endpoint URL for Prod stage for Save function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save/"
  LoadApi:
    Description: "API Gateway endpoint URL for Prod stage for Load function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/load/"
  SaveFunction:
    Description: "Pianobot Lambda Function ARN"
    Value: !GetAtt SaveFunction.Arn
  SaveFunctionIamRole:
    Description: "Implicit IAM Role created for Save function"
    Value: !GetAtt SaveFunctionRole.Arn
